services:
  db:
    image: postgres:18
    container_name: us_ev_market_share
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: us_ev_market_share
    ports:
      - "5440:5432" # Set port to 5440 for docker
    volumes:
      # Your datasets folder mounted into the container (read-only)
      - ./datasets:/datasets:ro

      # SQL scripts run automatically on first initialization
      - ./sql:/docker-entrypoint-initdb.d:ro
